# Generated by Django 3.1.7 on 2021-03-23 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_updated',
            new_name='dateUpdated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likedUsers',
            field=models.ManyToManyField(related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
