# Generated by Django 3.1.7 on 2021-03-23 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210323_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedUsers',
            field=models.ManyToManyField(null=True, related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
