# Generated by Django 3.1.7 on 2021-03-23 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210324_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedUsers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
