# Generated by Django 3.1.7 on 2021-03-23 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210324_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedUsers',
            field=models.ManyToManyField(blank=True, related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
