# Generated by Django 3.1.7 on 2021-03-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210327_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
