# Generated by Django 3.1.7 on 2021-03-29 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likedUsers',
            field=models.ManyToManyField(blank=True, related_name='likedComments', to=settings.AUTH_USER_MODEL),
        ),
    ]
