# Generated by Django 3.1.7 on 2021-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_comment_likedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
