# Generated by Django 3.1.7 on 2021-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20210331_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile_pic/default.jpg', upload_to='images/profile_pic/'),
        ),
    ]
